Add missing decls for malloc and realloc.
On macOS 13 and 15 the build failed with:

../../src/malloc_stub.c:47:20: error: call to undeclared library function 'malloc' with type 'void *(unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   47 |     return (void *)malloc(n);

This happens because malloc_stub.c contains:

void *
rpl_malloc(size_t n)
{
    if(n == 0) {
        n = 1;
    }
    return (void *)malloc(n);
}

config.h has:
/* Define to rpl_malloc if the replacement function should be used. */

So what's happening is:

void *
rpl_malloc(size_t n)
{
    if(n == 0) {
        n = 1;
    }
    return (void *)malloc(n);  // This is meant to call the "real" malloc but it isn't defined because it was declared as rpl_malloc.
}

If we look at the autoconf manual's entry for AC_FUNC_MALLOC, which is what
causes HAVE_MALLOC to be (not) ddefined it says:

  If the malloc function is compatible with the GNU C library malloc (i.e.,
  ‘malloc (0)’ returns a valid pointer), define HAVE_MALLOC to 1. Otherwise define
  HAVE_MALLOC to 0, ask for an AC_LIBOBJ replacement for ‘malloc’, and define
  malloc to rpl_malloc so that the native malloc is not used in the main project.

  Typically, the replacement file malloc.c should look like (note the ‘#undef malloc’):

       #include <config.h>
       #undef malloc

       #include <sys/types.h>

       void *malloc ();

       /* Allocate an N-byte block of memory from the heap.
	  If N is zero, allocate a 1-byte block.  */

       void *
       rpl_malloc (size_t n)
       {
	 if (n == 0)
	   n = 1;
	 return malloc (n);
       }
  The result of this macro is cached in the ac_cv_func_malloc_0_nonnull variable.

I don't know why the declarations were missing. They were missing when initially
added in commit f57ea5b6b589e2e1dbf35c214ab954260b2e6e74.